services:
  php:
    build: .
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network
    ports:
      - "8000:8000" # Porta do Laravel
    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - app-network
    ports:
      - "8080:80"

networks:
  app-network:

volumes:
  db_data:
